Module7 task1
htmlacademy-javascript/10069-keksobooking-22 pull request #9
Opened 2021-02-26 00:10 UTC by Alexey-og

2021-02-26 09:32 UTC, ademaro commented on js/create-fetch.js
> +  fetch('https://22.javascript.pages.academy/keksobooking/data')
https://22.javascript.pages.academy/keksobooking/data — в константу предлагаю

2021-02-26 09:32 UTC, ademaro commented on js/create-fetch.js
> +const getData = (onSuccess) => {
где тут onFail ?)

2021-02-26 09:33 UTC, ademaro commented on js/create-fetch.js
> +      body,
timeout мы не задаём?..

2021-02-26 09:34 UTC, ademaro commented on js/data.js
> +  bungalow: 'Бунгало',
почему решил сменить ключ?

2021-02-26 09:37 UTC, ademaro commented on js/data.js
>  }
моки-то удаляем теперь?

2021-02-26 09:39 UTC, ademaro commented on js/render-announcement.js
> +const AccommodationTypes = {
минимум третий раз встречаю) давай вынесем куда-нибудь))

2021-02-26 09:40 UTC, ademaro requested changes
Предлагаю оставить пока открытым ПР, можем созвониться или чатом пиши, все моменты закроем, двигаемся к идеалу)

2021-02-27 11:05 UTC, Alexey-og commented on js/create-fetch.js
> +  fetch('https://22.javascript.pages.academy/keksobooking/data')
Как принято называть URL сервера, с которого получают данные?

2021-02-27 11:06 UTC, Alexey-og commented on js/create-fetch.js
> +const getData = (onSuccess) => {
С этим "onFail" я пока не понимаю, что к чему. Взял с презентации по учебному проекту.

2021-02-27 11:13 UTC, Alexey-og commented on js/create-fetch.js
> +      body,
А для чего здесь нужен timeout?
Чтобы пользователя не шокировать слишком быстрым показом попапа?

2021-02-27 11:14 UTC, Alexey-og commented on js/data.js
> +  bungalow: 'Бунгало',
Ключ поправил на тот, который написан в данных, получаемых с сервера.

2021-02-27 11:20 UTC, Alexey-og commented on js/data.js
>  }
Нужно удалить сам файл "data.js" ?
А так я уже переделываю код, чтобы ничего не связывало с файлом "data.js", убираю импорт из этого модуля.
Собственно поэтому и пока появилось дублирование некоторых переменных. Копирую из файла "data.js" те переменные, которые нужны в других модулях. Чтобы, если и придется удалять "data.js", ничего не сломалось.

2021-02-27 11:27 UTC, Alexey-og commented on js/render-announcement.js
> +const AccommodationTypes = {
Эта переменная будет жить теперь в этом модуле. Готовлю проект к тому, что с файлом "data.js" уже ничего не будет связывать.

Сам файл "data.js" я хочу переименовать в "mock.js", чтобы логичнее было. Хотя сейчас это уже неважно, пускай дальше в проекте будет этот модуль с более логичным названием.

2021-02-27 14:42 UTC, ademaro commented on js/create-fetch.js
> +const getData = (onSuccess) => {
Понимаешь вообще что такое callback-функция?

2021-02-27 14:43 UTC, ademaro commented on js/create-fetch.js
> +  fetch('https://22.javascript.pages.academy/keksobooking/data')
Да нет особого соглашения... `const Url = { UPLOAD: 'https...', DOWNLOAD: '..' }` вот один из вариантов

2021-02-27 14:45 UTC, ademaro commented on js/create-fetch.js
> +      body,
Нет, я про сетевой таймаут, если сервер не получил данные за время по-умолчанию...

2021-02-27 14:46 UTC, ademaro commented on js/data.js
> +  bungalow: 'Бунгало',
мы можем преобразовывать данные, паттерн Адаптер)

2021-02-27 14:47 UTC, ademaro commented on js/data.js
> +  bungalow: 'Бунгало',
вообще рекомендую почитать про паттерны https://refactoring.guru/ru/design-patterns

2021-02-27 14:48 UTC, ademaro commented on js/data.js
>  }
да, data.js удаляем, если что-то понадобится — всегда есть в истории гита

2021-02-27 14:48 UTC, ademaro approved these changes

2021-02-27 14:48 UTC, merged